public with sharing class RC_ResumeUpload {
    
    // Global variables
    public String success           {   get; set;   } 
    public Attachment objAttachment {   get; set;   }


    // Constructor
    public RC_ResumeUpload() 
    {
        success = '';
        objAttachment = new Attachment();
        
        if(ApexPages.currentpage().getParameters().containsKey('Success'))  
            success = String.escapeSingleQuotes( ApexPages.currentpage().getParameters().get('Success') );
    }
    
    /* Start - Method for uploading file for chatter post.
       @Name           - insertContent
       @Parameters     - None 
       @Return Type    - pagereference
       @Description    - Function for uploading file
    */
    public Pagereference insertContent() 
    {
        try 
        {
            Pagereference objPR;
            TR1__TalentRoverProperties__c objCSTR = TR1__TalentRoverProperties__c.getInstance();
            String orgId = objCSTR.TR1__Organization_ID__c; 
            
            TR1.Candidate candt = TR1.ResumeProcessor.createUpdateContact(objAttachment, orgId);
            
            
            
            
            
            //Textra code does , resume parsing and create Contact Document record based on attachment and update the Contact record as well
            //TR1.Candidate candt = TR1.ResumeProcessor.createUpdateContact(objAttachment, UserInfo.getSessionId());
         
            
            if(String.isNotEmpty(candt.DeleteCandidateId)){
                Contact objContact = [Select Id from Contact where TR1__External_Candidate_Id__c=:candt.DeleteCandidateId];
                
                List<User> lstUser = [Select Id from User where ContactId =:objContact.Id ];
                 
                if(!lstUser.isEmpty())
                {
                    delete [Select Name from TR1__ContactDocument__c where TR1__Contact__c =:objContact.Id  Order BY CreatedDate Desc limit 1];
                    return new Pagereference('/ResumeUpload?Success=uploaded&UserExist=true&cId='+objContact.Id);
                }
                 
            }
            
            // candt = TR1.ResumeProcessor.performDML(candt);
            try {
            if(candt.IsParserError != true && candt.con != null){
                upsert candt.con;
                if(candt.ContactId == null) candt.ContactId = candt.con.Id;
                if(candt.Resume.ParentId == null) candt.Resume.ParentId = candt.con.Id;
                candt.ResumeView.ParentId = candt.con.Id;                    
                if(candt.Resume.Id == null && candt.Resume.ParentId != null){
                    insert candt.Resume;                
                }                
                if(candt.ResumeView.Id == null && candt.ResumeView.ParentId != null){
                    insert candt.ResumeView;                
                }                
                TR1__ContactDocument__c cd = new TR1__ContactDocument__c();
                cd.TR1__Contact__c = candt.ContactId;
                cd.Name = candt.Resume.Name.length()> 80? candt.Resume.Name.subString(0,79):candt.Resume.Name;
                String host;
                if(TR1__TalentRoverProperties__c.getOrgDefaults() != null && TR1__TalentRoverProperties__c.getOrgDefaults().TR1__Salesforce_Host__c != null && TR1__TalentRoverProperties__c.getOrgDefaults().TR1__Salesforce_Host__c.trim() != '')                
                    host = 'https://'+ TR1__TalentRoverProperties__c.getOrgDefaults().TR1__Salesforce_Host__c;
                else
                    host = URL.getSalesforceBaseUrl().toExternalForm().replace('visual','content');                                    
                cd.TR1__Internal_URL__c = host +'/servlet/servlet.FileDownload?file='+ candt.Resume.Id;
                cd.TR1__Internal_View_URL__c = host +'/servlet/servlet.FileDownload?file='+candt.ResumeView.Id;
                cd.TR1__Type__c = 'Resume';
                cd.TR1__Version__c = candt.con.TR1__Recent_Resume_Version__c !=null ? candt.con.TR1__Recent_Resume_Version__c + 1 : 1;
                cd.TR1__isDefault__c = true;
                cd.TR1__Convert_to_Content_Document__c = false;
                cd.TR1__Delete_Attachment__c = false;
                insert cd; 
                
                //START Added by LnMedikonda for story S-302 
                TR1__TalentRoverProperties__c trProrps = TR1__TalentRoverProperties__c.getOrgDefaults();
                if(candt.EducationList.size() > 0 && (candt.IsNewContact || trProrps.TR1__UpdateExistingEducationHistory__c)){
                    List<TR1__EducationHistory__c> historyRecordsToInsert = new List<TR1__EducationHistory__c>();
                    Map<String, TR1__EducationHistory__c> EhExtMap = new Map<String, TR1__EducationHistory__c>();
                    for(TR1__EducationHistory__c edu : [Select Id,TR1__EducationHistoryExtID__c 
                        from TR1__EducationHistory__c Where TR1__Contact__c = :candt.ContactId]){
                        EhExtMap.put(edu.TR1__EducationHistoryExtID__c, edu);
                    }
                    
                    for(TR1__EducationHistory__c edu: candt.EducationList){
                        edu.TR1__Contact__c = candt.ContactId;
                        String key = edu.TR1__SchoolName__c +':'+ edu.TR1__SchoolType__c;
                        if(EhExtMap.containsKey(key)){
                            /*sObject ob = edu;
                            ob.put('Id', EhExtMap.get(key).Id);
                            edu = (TR1__EducationHistory__c)ob;*/
                        }else{
                            historyRecordsToInsert.add(edu);
                        }
                    }
                    upsert historyRecordsToInsert;
                }
                
                if(candt.EmploymentList.size() > 0 && (candt.IsNewContact || trProrps.TR1__UpdateExistingWorkHistory__c)){
                    List<TR1__EmploymentHistory__c> historyRecordsToInsert = new List<TR1__EmploymentHistory__c>();
                    Map<String, TR1__EmploymentHistory__c> EhExtMap = new Map<String, TR1__EmploymentHistory__c>();
                    for(TR1__EmploymentHistory__c emp : [Select Id,TR1__EmployeeHistoryExtID__c 
                        from TR1__EmploymentHistory__c Where TR1__Contact__c = :candt.ContactId]){
                        EhExtMap.put(emp.TR1__EmployeeHistoryExtID__c, emp);
                    }
                    
                    for(TR1__EmploymentHistory__c emp: candt.EmploymentList){
                        emp.TR1__Contact__c = candt.ContactId;
                        String key = emp.TR1__Title__c!=null?emp.TR1__Title__c+':' :''+':';
                        key +=emp.TR1__EmployerName__c!=null?emp.TR1__EmployerName__c+':':''+':';
                        key +=emp.TR1__StartDate__c!=null?emp.TR1__StartDate__c:'';
                        if(EhExtMap.containsKey(key)){
                            /*sObject ob = emp;
                            ob.put('Id', EhExtMap.get(key).Id);
                            emp = (TR1__EmploymentHistory__c)ob;*/
                        }else{
                            historyRecordsToInsert.add(emp);
                        }
                    }
                    upsert historyRecordsToInsert; 
                }        
            }
        }
        catch(DMLException dmlex){
            candt.IsParserError = true;            
            candt.ParserErrorMsg =  dmlex.getMessage(); 
        }
        catch(Exception ex){
            candt.IsParserError = true;
            candt.ParserErrorMsg =  ex.getMessage();
        }
        finally{
            candt.Resume.Body = null;
            candt.Resume = new Attachment();
        } 
            
          	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new List<String>{objCSTR.Apex_Email_Service__c});
            email.setSubject(candt.ContactId);
            email.setPlainTextBody('');
            List<Messaging.SendEmailResult> result = Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
           
            objPR = new Pagereference('/ResumeUpload?Success=uploaded&UserExist=false&cId='+candt.ContactId); 
            objPR.setredirect(true); 
             
            objAttachment = new Attachment();
            if(Test.isRunningTest())
                Integer i = 1/0;
            return objPR; 
        }
        catch(Exception e)
        {
            system.debug(':::exception:::'+e);
            System.debug('--- e.getLineNumber() : '+e.getLineNumber());
            System.debug('---- getStackTraceString '+e.getStackTraceString());
            objAttachment = new Attachment();
            Pagereference objPR = new Pagereference('/ResumeUpload?Success=false&UserExist=false');
            objPR.setredirect(true);
            return objPR;
        }
    }
    /* End - insertContent method */
    

    
}